### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by drolfe** [josqu4red/ilorb#3]
Hi Sorry to be a pain, but I'm only getting started with ruby and would love some more examples of passing in data to the more complex definitions such as below for example

write_cmd :server_auto_pwr do
    attributes :value

write_cmd :set_persistent_boot do
    elements :device => [ :value ]

write_cmd :set_pwreg do
    elements :pwralert => :type, :pwralert_settings => [:threshold, :duration]

I plan to make a very basic Sinatra app to admin our servers.

**Comment by josqu4red** [comment]
That's probably way too late, but there were some examples in tests for ```set_persistent_boot``` and ```set_pwreg```, hope you figured it out. I just added one for ```server_auto_pwr```.
Sorry for the delay.
